CREATE TABLE articles (
id SUUID DEFAULT uuid_generate_v4()  PRIMARY KEY,
title VARCHAR(100) NOT NULL,
status article_status NOT NULL,
category_id UUID FOREIGN KEY REFERENCES categories(id),
image TEXT NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMP NOT NULL,
updated_at TIMESTAMP NOT NULL, 
created_by UUID FOREIGN KEY REFERENCES users(id),
updated_by UUID FOREIGN KEY REFERENCES users(id),
);


CREATE TABLE categories (
id UUID DEFAULT uuid_generate_v4 () PRIMARY KEY,
name VARCHAR(50) NOT NULL,
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT,
);

CREATE TABLE users (
id SERIAL PRIMARY KEY,
email VARCHAR(200) NOT NULL UNIQUE,
password VARCHAR(200) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);